### ISSUE TITLE
non-root = error

### ISSUE THREAD

**Issue by jschwalbe** [EricTerrell/TrashCanMonitor#1]
Hi there, trying out your code and it seems I cannot run it without being root. Any ideas? Thanks!

```
$ python3 TrashCanMonitor.py 30 trashcan-stats.csv

wait_seconds:     30
output_file_path: trashcan-stats.csv

Traceback (most recent call last):
  File "/Users/ob1/Downloads/TrashCanMonitor.py", line 208, in <module>
    main()
  File "/Users/ob1/Downloads/TrashCanMonitor.py", line 198, in main
    record_stats(ping_ip_address, timeout_seconds, simultaneous_pings, target_url, output)
  File "/Users/ob1/Downloads/TrashCanMonitor.py", line 58, in record_stats
    result = ping(target, timeout, count)
  File "/usr/local/lib/python3.9/site-packages/pythonping/__init__.py", line 73, in ping
    comm = executor.Communicator(target, provider, timeout, socket_options=options, verbose=verbose, output=out,
  File "/usr/local/lib/python3.9/site-packages/pythonping/executor.py", line 247, in __init__
    self.socket = network.Socket(target, 'icmp', source=None, options=socket_options)
  File "/usr/local/lib/python3.9/site-packages/pythonping/network.py", line 33, in __init__
    self.socket = socket.socket(socket.AF_INET, socket.SOCK_RAW, self.protocol)
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 232, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
PermissionError: [Errno 1] Operation not permitted

```

**Comment by EricTerrell** [comment]
Hi,

Is running it using the sudo command a non-starter for you? I'm not sure if that's something that I can control in the source code.

Sincerely,

Eric Bergman-Terrell

**Comment by jschwalbe** [comment]
Hi. No, I suppose not. Once the location is perfected I suppose it's not something I'll need to keep using. I started the issue before realizing sudo fixed the error, then edited it a bit. No worries! Thank you
